/* Generated By:JJTree: Do not edit this line. CaptureAttrsFunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.googlecode.axs.xpath;

public
class CaptureAttrsFunction extends SimpleNode {
  public CaptureAttrsFunction(int id) {
    super(id);
  }

  public CaptureAttrsFunction(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, com.googlecode.axs.ShortVector data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=40375cdd1ed83fa02d650538a2f0bcd0 (do not edit this line) */
