/* Generated By:JJTree: Do not edit this line. Expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.googlecode.axs.xpath;

public
class Expression extends SimpleNode {
  public Expression(int id) {
    super(id);
  }

  public Expression(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, com.googlecode.axs.ShortVector data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4bda1b904d2ff13bbe4d53bb15f70302 (do not edit this line) */
