/* Generated By:JavaCC: Do not edit this line. ParserVisitor.java Version 5.0 */
package com.googlecode.axs.xpath;

public interface ParserVisitor
{
  public Object visit(SimpleNode node, com.googlecode.axs.ShortVector data);
  public Object visit(Start node, com.googlecode.axs.ShortVector data);
  public Object visit(Expression node, com.googlecode.axs.ShortVector data);
  public Object visit(Slash node, com.googlecode.axs.ShortVector data);
  public Object visit(SlashSlash node, com.googlecode.axs.ShortVector data);
  public Object visit(StepExpression node, com.googlecode.axs.ShortVector data);
  public Object visit(Predicate node, com.googlecode.axs.ShortVector data);
  public Object visit(OrExpression node, com.googlecode.axs.ShortVector data);
  public Object visit(AndExpression node, com.googlecode.axs.ShortVector data);
  public Object visit(NotExpression node, com.googlecode.axs.ShortVector data);
  public Object visit(NumericComparisonExpression node, com.googlecode.axs.ShortVector data);
  public Object visit(StringComparisonExpression node, com.googlecode.axs.ShortVector data);
  public Object visit(StringSearchFunction node, com.googlecode.axs.ShortVector data);
  public Object visit(IntegerValue node, com.googlecode.axs.ShortVector data);
  public Object visit(StringValue node, com.googlecode.axs.ShortVector data);
  public Object visit(AttributeExpression node, com.googlecode.axs.ShortVector data);
  public Object visit(CaptureAttrsFunction node, com.googlecode.axs.ShortVector data);
  public Object visit(PositionFunction node, com.googlecode.axs.ShortVector data);
  public Object visit(NameValue node, com.googlecode.axs.ShortVector data);
}
/* JavaCC - OriginalChecksum=94de1446424ed0633790099ee9c33a91 (do not edit this line) */
