package com.googlecode.axs;

/**
 * This is thrown if a handler's autogenerated _AXSData extension is unable to find
 * a call for a given id. It should never happen. 
 * @author Ben
 *
 */
public class HandlerCallError extends Error {
	private static final long serialVersionUID = 671966460457946905L;

	public HandlerCallError() {
	}

	public HandlerCallError(String arg0) {
		super(arg0);
	}

	public HandlerCallError(Throwable arg0) {
		super(arg0);
	}

	public HandlerCallError(String arg0, Throwable arg1) {
		super(arg0, arg1);
	}

}
