/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package com.googlecode.axs.xpath;

public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPRESSION = 1;
  public int JJTABSOLUTEPATHEXPRESSION = 2;
  public int JJTVOID = 3;
  public int JJTCHILDEXPRESSION = 4;
  public int JJTDECENDENTEXPRESSION = 5;
  public int JJTWILDCARD = 6;
  public int JJTPREDICATE = 7;
  public int JJTOREXPRESSION = 8;
  public int JJTANDEXPRESSION = 9;
  public int JJTCOMPARISONEXPRESSION = 10;
  public int JJTINTEGER = 11;
  public int JJTSTRING = 12;
  public int JJTATTRIBUTEEXPRESSION = 13;
  public int JJTFUNCTIONEXPRESSION = 14;
  public int JJTNAME = 15;


  public String[] jjtNodeName = {
    "Start",
    "Expression",
    "AbsolutePathExpression",
    "void",
    "ChildExpression",
    "DecendentExpression",
    "Wildcard",
    "Predicate",
    "OrExpression",
    "AndExpression",
    "ComparisonExpression",
    "Integer",
    "String",
    "AttributeExpression",
    "FunctionExpression",
    "Name",
  };
}
/* JavaCC - OriginalChecksum=1874abf15e74310e5ac982f5d8be1ed4 (do not edit this line) */
