/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package com.googlecode.axs.xpath;

public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPRESSION = 1;
  public int JJTSLASH = 2;
  public int JJTSLASHSLASH = 3;
  public int JJTSTEPEXPRESSION = 4;
  public int JJTVOID = 5;
  public int JJTPREDICATE = 6;
  public int JJTOREXPRESSION = 7;
  public int JJTANDEXPRESSION = 8;
  public int JJTNOTEXPRESSION = 9;
  public int JJTNUMERICCOMPARISONEXPRESSION = 10;
  public int JJTSTRINGCOMPARISONEXPRESSION = 11;
  public int JJTSTRINGSEARCHFUNCTION = 12;
  public int JJTINTEGERVALUE = 13;
  public int JJTSTRINGVALUE = 14;
  public int JJTATTRIBUTEEXPRESSION = 15;
  public int JJTCAPTUREATTRSFUNCTION = 16;
  public int JJTPOSITIONFUNCTION = 17;
  public int JJTFUNCTIONEXPRESSION = 18;
  public int JJTNAMEVALUE = 19;


  public String[] jjtNodeName = {
    "Start",
    "Expression",
    "Slash",
    "SlashSlash",
    "StepExpression",
    "void",
    "Predicate",
    "OrExpression",
    "AndExpression",
    "NotExpression",
    "NumericComparisonExpression",
    "StringComparisonExpression",
    "StringSearchFunction",
    "IntegerValue",
    "StringValue",
    "AttributeExpression",
    "CaptureAttrsFunction",
    "PositionFunction",
    "FunctionExpression",
    "NameValue",
  };
}
/* JavaCC - OriginalChecksum=ad6e9128efabd4565f5c6b17007570a1 (do not edit this line) */
