/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package com.googlecode.axs.xpath;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 6;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 8;
  /** RegularExpression Id. */
  int DQUOT_LITERAL = 9;
  /** RegularExpression Id. */
  int SQUOT_LITERAL = 10;
  /** RegularExpression Id. */
  int EQ = 11;
  /** RegularExpression Id. */
  int NE = 12;
  /** RegularExpression Id. */
  int LT = 13;
  /** RegularExpression Id. */
  int GT = 14;
  /** RegularExpression Id. */
  int LE = 15;
  /** RegularExpression Id. */
  int GE = 16;
  /** RegularExpression Id. */
  int NAME = 35;
  /** RegularExpression Id. */
  int NAME_START_CHAR = 36;
  /** RegularExpression Id. */
  int NAME_CHAR = 37;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"(:\"",
    "\"*)\"",
    "<token of kind 7>",
    "<INTEGER_LITERAL>",
    "<DQUOT_LITERAL>",
    "<SQUOT_LITERAL>",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"|\"",
    "\"/\"",
    "\"//\"",
    "\"[\"",
    "\"]\"",
    "\"or\"",
    "\"and\"",
    "\"(\"",
    "\")\"",
    "\"not\"",
    "\"contains\"",
    "\"starts-with\"",
    "\"ends-with\"",
    "\",\"",
    "\"attribute::\"",
    "\"@\"",
    "\"captureattrs\"",
    "\"position\"",
    "<NAME>",
    "<NAME_START_CHAR>",
    "<NAME_CHAR>",
  };

}
