/* This class is autogenerated by the AXS compiler. Do not edit! */

/* **********************************************************************************/
/* Copyright (c) 2013 Benjamin K. Stuhl                                             */
/*                                                                                  */
/* Permission is hereby granted, free of charge, to any person obtaining a copy     */
/* of this software and associated documentation files (the "Software"), to deal    */
/* in the Software without restriction, including without limitation the rights     */
/* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies */
/* of the Software, and to permit persons to whom the Software is furnished to do   */
/* so, subject to the following conditions:                                         */
/*                                                                                  */
/* The above copyright notice and this permission notice shall be included in all   */
/* copies or substantial portions of the Software.                                  */
/*                                                                                  */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR       */
/* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,         */
/* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE      */
/* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER           */
/* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,    */
/* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE    */
/* SOFTWARE.                                                                        */
/* **********************************************************************************/

package com.googlecode.axs.tests;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import javax.annotation.Generated;
import org.xml.sax.Attributes;
import org.xml.sax.SAXException;

import com.googlecode.axs.AXSData;
import com.googlecode.axs.AbstractAnnotatedHandler;
import com.googlecode.axs.HandlerCallError;
import com.googlecode.axs.QName;
import com.googlecode.axs.XPathExpression;

import com.googlecode.axs.tests.RuntimeTest4;


@Generated(value = { "com.googlecode.axs.AnnotationProcessor", "com.googlecode.axs.tests.RuntimeTest4"})
public class RuntimeTest4_AXSData implements AXSData {
    private static Object Lock = new Object();

    @Override
    public void callXPathText(AbstractAnnotatedHandler abstractHandler, int exprIx, String callbackArg) throws SAXException {
        RuntimeTest4 handler = (RuntimeTest4) abstractHandler;

        switch (exprIx) {
        case 0: 
            // "italic//bold"
            handler.testPredicateRetrial(callbackArg);
            break;
        default: throw new HandlerCallError("unhandled call #" + exprIx);
        }
    }

    @Override
    public void callXPathEnd(AbstractAnnotatedHandler abstractHandler, int exprIx) throws SAXException {
        RuntimeTest4 handler = (RuntimeTest4) abstractHandler;

        switch (exprIx) {
        default: throw new HandlerCallError("unhandled call #" + exprIx);
        }
    }

    @Override
    public void callXPathStart(AbstractAnnotatedHandler abstractHandler, int exprIx, Attributes callbackArg) throws SAXException {
        RuntimeTest4 handler = (RuntimeTest4) abstractHandler;

        switch (exprIx) {
        default: throw new HandlerCallError("unhandled call #" + exprIx);
        }
    }

    @Override
    public int getAXSDataVersion() {
        return 65536;
    }

    @Override
    public int getNumberOfCapturingExpressions() {
        return 1;
    }

    @Override
    public int getNumberOfEndExpressions() {
        return 0;
    }

    @Override
    public int getMaximumPredicateStackDepth() {
        return 0;
    }

    private static HashMap<String, int[]> Triggers = null;

    @Override
    public Map<String, int[]> getTriggerTags() {
        synchronized (Lock) {
            if (Triggers != null)
                return Triggers;
            Triggers = new HashMap<String, int[]>();
            Triggers.put("bold", 
                    new int[] { 0, });
        }
        return Triggers;
    }

    private static HashSet<String> AttributeCaptureTags = null;

    @Override
    public Set<String> getAttributeCaptureTags() {
        synchronized (Lock) {
            if (AttributeCaptureTags != null)
                return AttributeCaptureTags;

            AttributeCaptureTags = new HashSet<String>();
        }
        return AttributeCaptureTags;
    }

    private static HashSet<String> PositionCaptureTags = null;

    @Override
    public Set<String> getPositionCaptureTags() {
        synchronized (Lock) {
            if (PositionCaptureTags != null)
                return PositionCaptureTags;

            PositionCaptureTags = new HashSet<String>();
        }
        return PositionCaptureTags;
    }

    private static String[] Literals = new String[] {
    };

    private static QName[] QNames = new QName[] {
        new QName("", "bold"),
        new QName("", "italic"),
    };

    private static XPathExpression[] Expressions = new XPathExpression[] {
        new XPathExpression( // "italic//bold"
        new short[] {
            XPathExpression.INSTR_ELEMENT, 0,
            XPathExpression.INSTR_NONCONSECUTIVE_ELEMENT, 1,
            XPathExpression.INSTR_ELEMENT, 1,
        }, QNames, Literals),
    };

    public XPathExpression[] getXPathExpressions() {
        return Expressions;
    }
}
